#pragma once
// Vector
#include "./implementations/vector/vectorDouble.hpp"
#include "./implementations/vector/vectorFloat.hpp"
#include "./implementations/vector/vectorInt.hpp"
#include "./implementations/vector/vectorUint8_t.hpp"
#include "./implementations/vector/vectorUint64_t.hpp"
// Matrix
#include "./implementations/matrix/matrixDouble.hpp"
#include "./implementations/matrix/matrixFloat.hpp"
#include "./implementations/matrix/matrixUint8_t.hpp"
// Functions
#include "./implementations/functions/binarySearch.hpp"
#include "./implementations/functions/clip.hpp"
#include "./implementations/functions/concatenate.hpp"
#include "./implementations/functions/cout.hpp"
#include "./implementations/functions/dot.hpp"
#include "./implementations/functions/kernelDensity.hpp"
#include "./implementations/functions/randomGenerator.hpp"
#include "./implementations/functions/reversedOperators.hpp"
#include "./implementations/functions/vectorize.hpp"
#include "./implementations/functions/where.hpp"